version: '2.1'

services:
  angular-docker-demo:
    image: angular-docker-demo
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9090:9090
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js